#!/usr/bin/env bash
# Cloud Agent install script for Habicht (Swiss Volleyball Scouting Platform).
# Idempotent: safe to run repeatedly and against cached/snapshotted state.
set -euo pipefail

# Move to repository root (this script lives in <repo>/.cursor).
cd "$(dirname "$0")/.."

echo "==> [1/6] Ensuring PostgreSQL is installed"
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq postgresql postgresql-contrib
fi

# Detect the installed PostgreSQL major version / cluster name.
PG_VER="$(ls /etc/postgresql 2>/dev/null | sort -V | tail -1 || true)"
PG_VER="${PG_VER:-16}"
PG_CLUSTER="main"

echo "==> [2/6] Starting PostgreSQL cluster ${PG_VER}/${PG_CLUSTER}"
sudo pg_ctlcluster "${PG_VER}" "${PG_CLUSTER}" start 2>/dev/null || true
for _ in $(seq 1 30); do
  if sudo -u postgres pg_isready -q 2>/dev/null; then break; fi
  sleep 1
done

echo "==> [3/6] Creating database role and database (idempotent)"
sudo -u postgres psql -v ON_ERROR_STOP=1 <<'SQL'
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'habicht') THEN
    CREATE ROLE habicht LOGIN PASSWORD 'habicht';
  END IF;
END
$$;
SQL
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='habicht_db'" | grep -q 1; then
  sudo -u postgres psql -v ON_ERROR_STOP=1 -c "CREATE DATABASE habicht_db OWNER habicht;"
fi
sudo -u postgres psql -v ON_ERROR_STOP=1 -c "GRANT ALL PRIVILEGES ON DATABASE habicht_db TO habicht;"

echo "==> [4/6] Writing local .env (only if missing)"
if [ ! -f .env ]; then
  SECRET="$(openssl rand -base64 32)"
  cat > .env <<EOF
# Local development environment for Cloud Agents (generated by .cursor/install.sh)
DATABASE_URL="postgresql://habicht:habicht@localhost:5432/habicht_db?schema=public"

NEXTAUTH_URL="http://localhost:3000"
NEXTAUTH_SECRET="${SECRET}"
NEXT_PUBLIC_APP_URL="http://localhost:3000"

# Optional integrations. Uploads are disabled and emails are logged to the
# dev-server console while these are blank. Add real values as Cloud Agent
# secrets if you need Cloudinary uploads or Resend email delivery.
CLOUDINARY_CLOUD_NAME=""
CLOUDINARY_API_KEY=""
CLOUDINARY_API_SECRET=""
NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=""
NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET=""
RESEND_API_KEY=""

SWISS_VOLLEY_API_URL="https://www.volleyball.ch/api"
SWISS_VOLLEY_API_KEY=""
EOF
fi

echo "==> [5/6] Installing Node dependencies (npm ci; runs prisma generate)"
npm ci

echo "==> [6/6] Syncing Prisma schema to the database"
npx prisma db push --skip-generate

echo "==> Install complete."
