'use client'

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react'
import { translateText, getGoogleLanguageCode } from '@/lib/translate'

type Language = 'gsw' | 'de' | 'fr' | 'it' | 'rm' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
  translate: (text: string, sourceLanguage?: string) => Promise<string>
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  gsw: {
    // Gender
    'gender.male': 'Männlich',
    'gender.female': 'Wiiblich',
    // Login
    'login.title': 'Aamelde',
    'login.button': 'Aamelde',
    'login.loading': 'Wird Aameldet...',
    'login.register': 'erstell es neus Konto',
    'login.or': 'Oder',
    'login.email': 'Email Adresse',
    'login.password': 'Passwort',
    'login.rememberMe': 'Aameldet Bliibe',
    'login.forgotPassword': 'Passwort Vergässe?',
    // Chat
    'chat.writeMessage': 'Nachricht Schriihe...',
    'chat.addEmoji': 'Emoji Hinzuefüege',
    // Common
    'common.save': 'Speichere',
    'common.cancel': 'Abbräche',
    'common.delete': 'Lösche',
    'common.edit': 'Bearbeite',
    'common.search': 'Sueche',
    'common.filter': 'Filtere',
    'common.loading': 'Lade...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.back': 'Zrugg',
    'common.next': 'Wiiter',
    'common.submit': 'Abschicke',
    // Navigation
    'nav.home': 'Hei',
    'nav.players': 'Spieler',
    'nav.recruiters': 'Rekrutierer',
    'nav.clubs': 'Verein',
    'nav.about': 'Über Üs',
    'nav.settings': 'Iistellige',
    'nav.logout': 'Abmelde',
    'nav.login': 'Aamelde',
    'nav.register': 'Registriere',
    // Settings
    'settings.title': 'Iistellige',
    'settings.subtitle': 'Verwalte Dini Präferenzä Und Konto Iistellige',
    'settings.appearance': 'Uussehe',
    'settings.security': 'Login & Sicherheit',
    'settings.language': 'Sprache',
    'settings.notifications': 'Benachrichtigungen',
    'settings.account': 'Kontoverwaltung',
    'settings.appearance.title': 'Erscheinungsbild',
    'settings.appearance.subtitle': 'Passen Sie aa, wie Habicht für Sie uusgseet',
    'settings.theme': 'Theme-Modus',
    'settings.theme.light': 'Hell',
    'settings.theme.dark': 'Dunkel',
    'settings.theme.light.desc': 'Helles Design mit traditioneller Farbgebung',
    'settings.theme.dark.desc': 'Dunkles Design für komfortables Arbeite bi wenig Liecht',
    'settings.security.title': 'Login & Sicherheit',
    'settings.security.subtitle': 'Verwalte Dis Passwort und Sicherheitsiistellige',
    'settings.privacy': 'Dateschutz',
    'settings.privacy.desc': 'Stüüre, welchi Informatione öffentlich sichtbar sind',
    'settings.email.show': 'E-Mail-Adresse Azeige',
    'settings.email.show.desc': 'Dini E-Mail-Adresse für anderi sichtbar mache',
    'settings.phone.show': 'Telefonnummer Azeige',
    'settings.phone.show.desc': 'Dini Telefonnummer für anderi sichtbar mache',
    'settings.email': 'E-Mail-Adresse',
    'settings.password.change': 'Passwort Ändere',
    'settings.password.current': 'Aktuells Passwort',
    'settings.password.new': 'Neus Passwort',
    'settings.password.confirm': 'Passwort bestätige',
    'settings.password.button': 'Passwort ändere',
    'settings.language.title': 'Sprache',
    'settings.language.subtitle': 'Wähl Dini bevorzugti Sprache',
    'settings.notifications.title': 'Benachrichtigungen',
    'settings.notifications.subtitle': 'Leg fest, welli E-Mail Benachrichtigunge du empfange möchtsch',
    'settings.notifications.chat': '💬 Chat Nachrichtä',
    'settings.notifications.chat.description': 'Erhalt E-Mail Benachrichtigunge für neui Chat Nachrichtä',
    'settings.notifications.playerLooking': '🏐 Spieler Suecht Club',
    'settings.notifications.playerLooking.description': 'Benachrichtigunge wenn e Spieler aktiv e Club suecht',
    'settings.notifications.recruiterSearching': '🔍 Recruiter Suecht Spieler',
    'settings.notifications.recruiterSearching.description': 'Benachrichtigunge wenn Recruiters aktiv Spieler sueched',
    'settings.notifications.note.title': 'Hinweis:',
    'settings.notifications.note.description': 'Du chasch die Benachrichtigunge jederzit wieder aktiviere oder deaktiviere.',
    'settings.account.title': 'Kontoverwaltung',
    'settings.account.subtitle': 'Verwalte Dis Konto oder lösch es',
    'settings.password.current.placeholder': 'Aktuells Passwort iigee',
    'settings.password.new.placeholder': 'Neus Passwort iigee',
    'settings.password.confirm.placeholder': 'Passwort ernüüt iigee',
    'settings.theme.light.description': 'Helles Design mit traditioneller Farbgebung',
    'settings.theme.dark.description': 'Dunkles Design für komfortables Arbeite bi wenig Liecht',
    'settings.privacy.subtitle': 'Stüüre, welchi Informatione öffentlich sichtbar sind',
    'settings.email.show.description': 'Dini E-Mail-Adresse für anderi sichtbar mache',
    'settings.phone.show.description': 'Dini Telefonnummer für anderi sichtbar mache',
    'settings.saved': 'Iistellunge Gspeichert',
  },
  de: {
    // Gender
    'gender.male': 'Männlich',
    'gender.female': 'Weiblich',
    // Login
    'login.title': 'Anmelden',
    'login.button': 'Anmelden',
    'login.loading': 'Wird angemeldet...',
    'login.register': 'Erstelle ein neues Konto',
    'login.or': 'Oder',
    'login.email': 'Email Adresse',
    'login.password': 'Passwort',
    'login.rememberMe': 'Angemeldet bleiben',
    'login.forgotPassword': 'Passwort vergessen?',
    // Chat
    'chat.writeMessage': 'Nachricht schreiben...',
    'chat.addEmoji': 'Emoji hinzufügen',
    // Common
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.search': 'Suchen',
    'common.filter': 'Filtern',
    'common.loading': 'Lädt...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.submit': 'Absenden',
    // Navigation
    'nav.home': 'Startseite',
    'nav.players': 'Spieler',
    'nav.recruiters': 'Rekrutierer',
    'nav.clubs': 'Vereine',
    'nav.about': 'Über uns',
    'nav.settings': 'Einstellungen',
    'nav.logout': 'Abmelden',
    'nav.login': 'Anmelden',
    'nav.register': 'Registrieren',
    // Settings
    'settings.title': 'Einstellungen',
    'settings.subtitle': 'Verwalten Sie Ihre Präferenzen und Kontoeinstellungen',
    'settings.appearance': 'Aussehen',
    'settings.security': 'Login & Sicherheit',
    'settings.language': 'Sprache',
    'settings.notifications': 'Benachrichtigungen',
    'settings.account': 'Kontoverwaltung',
    'settings.appearance.title': 'Erscheinungsbild',
    'settings.appearance.subtitle': 'Passen Sie an, wie Habicht für Sie aussieht',
    'settings.theme': 'Theme-Modus',
    'settings.theme.light': 'Hell',
    'settings.theme.dark': 'Dunkel',
    'settings.theme.light.desc': 'Helles Design mit traditioneller Farbgebung',
    'settings.theme.dark.desc': 'Dunkles Design für komfortables Arbeiten bei wenig Licht',
    'settings.security.title': 'Login & Sicherheit',
    'settings.security.subtitle': 'Verwalten Sie Ihr Passwort und Sicherheitseinstellungen',
    'settings.privacy': 'Datenschutz',
    'settings.privacy.desc': 'Steuern Sie, welche Informationen öffentlich sichtbar sind',
    'settings.email.show': 'E-Mail-Adresse Anzeige',
    'settings.email.show.desc': 'Ihre E-Mail-Adresse für andere sichtbar machen',
    'settings.phone.show': 'Telefonnummer Anzeige',
    'settings.phone.show.desc': 'Ihre Telefonnummer für andere sichtbar machen',
    'settings.email': 'E-Mail-Adresse',
    'settings.password.change': 'Passwort Ändern',
    'settings.password.current': 'Aktuelles Passwort',
    'settings.password.new': 'Neues Passwort',
    'settings.password.confirm': 'Passwort bestätigen',
    'settings.password.button': 'Passwort ändern',
    'settings.language.title': 'Sprache',
    'settings.language.subtitle': 'Wählen Sie Ihre bevorzugte Sprache',
    'settings.notifications.title': 'Benachrichtigungen',
    'settings.notifications.subtitle': 'Leg fest, welli E-Mail Benachrichtigunge du empfange möchtsch',
    'settings.notifications.chat': '💬 Chat Nachrichtä',
    'settings.notifications.chat.description': 'Erhalt E-Mail Benachrichtigunge für neui Chat Nachrichtä',
    'settings.notifications.playerLooking': '🏐 Spieler Suecht Club',
    'settings.notifications.playerLooking.description': 'Benachrichtigunge wenn e Spieler aktiv e Club suecht',
    'settings.notifications.recruiterSearching': '🔍 Recruiter Suecht Spieler',
    'settings.notifications.recruiterSearching.description': 'Benachrichtigunge wenn Recruiters aktiv Spieler sueched',
    'settings.notifications.note.title': 'Hinweis:',
    'settings.notifications.note.description': 'Du chasch die Benachrichtigunge jederzit wieder aktiviere oder deaktiviere.',
    'settings.account.title': 'Kontoverwaltung',
    'settings.account.subtitle': 'Verwalten Sie Ihr Konto oder löschen Sie es',
    'settings.password.current.placeholder': 'Aktuelles Passwort eingeben',
    'settings.password.new.placeholder': 'Neues Passwort eingeben',
    'settings.password.confirm.placeholder': 'Passwort erneut eingeben',
    'settings.theme.light.description': 'Helles Design mit traditioneller Farbgebung',
    'settings.theme.dark.description': 'Dunkles Design für komfortables Arbeiten bei wenig Licht',
    'settings.privacy.subtitle': 'Steuern Sie, welche Informationen öffentlich sichtbar sind',
    'settings.email.show.description': 'Ihre E-Mail-Adresse für andere sichtbar machen',
    'settings.phone.show.description': 'Ihre Telefonnummer für andere sichtbar machen',
    'settings.saved': 'Einstellungen Gespeichert',
  },
  fr: {
    // Gender
    'gender.male': 'Masculin',
    'gender.female': 'Féminin',
    // Login
    'login.title': 'Se connecter',
    'login.button': 'Se connecter',
    'login.loading': 'Connexion en cours...',
    'login.register': 'créer un nouveau compte',
    'login.or': 'Ou',
    'login.email': 'Adresse email',
    'login.password': 'Mot de passe',
    'login.rememberMe': 'Rester connecté',
    'login.forgotPassword': 'Mot de passe oublié?',
    // Chat
    'chat.writeMessage': 'Écrire un message...',
    'chat.addEmoji': 'Ajouter un emoji',
    // Common
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.submit': 'Soumettre',
    // Navigation
    'nav.home': 'Accueil',
    'nav.players': 'Joueurs',
    'nav.recruiters': 'Recruteurs',
    'nav.clubs': 'Clubs',
    'nav.about': 'À propos',
    'nav.settings': 'Paramètres',
    'nav.logout': 'Déconnexion',
    'nav.login': 'Connexion',
    'nav.register': 'S\'inscrire',
    // Settings
    'settings.title': 'Paramètres',
    'settings.subtitle': 'Gérez vos préférences et paramètres de compte',
    'settings.appearance': 'Apparence',
    'settings.security': 'Connexion & Sécurité',
    'settings.language': 'Langue',
    'settings.notifications': 'Notifications',
    'settings.account': 'Gestion du compte',
    'settings.appearance.title': 'Apparence',
    'settings.appearance.subtitle': 'Personnalisez l\'apparence de Habicht',
    'settings.theme': 'Mode thème',
    'settings.theme.light': 'Clair',
    'settings.theme.dark': 'Sombre',
    'settings.theme.light.desc': 'Design clair avec des couleurs traditionnelles',
    'settings.theme.dark.desc': 'Design sombre pour un travail confortable en faible luminosité',
    'settings.security.title': 'Connexion & Sécurité',
    'settings.security.subtitle': 'Gérez votre mot de passe et paramètres de sécurité',
    'settings.privacy': 'Confidentialité',
    'settings.privacy.desc': 'Contrôlez quelles informations sont publiquement visibles',
    'settings.email.show': 'Affichage de l\'adresse email',
    'settings.email.show.desc': 'Rendre votre adresse email visible aux autres',
    'settings.phone.show': 'Affichage du numéro de téléphone',
    'settings.phone.show.desc': 'Rendre votre numéro de téléphone visible aux autres',
    'settings.email': 'Adresse email',
    'settings.password.change': 'Changer le mot de passe',
    'settings.password.current': 'Mot de passe actuel',
    'settings.password.new': 'Nouveau mot de passe',
    'settings.password.confirm': 'Confirmer le mot de passe',
    'settings.password.button': 'Changer le mot de passe',
    'settings.language.title': 'Langue',
    'settings.language.subtitle': 'Choisissez votre langue préférée',
    'settings.notifications.title': 'Notifications',
    'settings.notifications.subtitle': 'Définissez les notifications par e-mail que vous souhaitez recevoir',
    'settings.notifications.chat': '💬 Messages du Chat',
    'settings.notifications.chat.description': 'Recevoir des notifications par e-mail pour les nouveaux messages du chat',
    'settings.notifications.playerLooking': '🏐 Joueur Cherche un Club',
    'settings.notifications.playerLooking.description': 'Notifications lorsqu\'un joueur cherche activement un club',
    'settings.notifications.recruiterSearching': '🔍 Recruteur Cherche un Joueur',
    'settings.notifications.recruiterSearching.description': 'Notifications lorsque les recruteurs cherchent activement des joueurs',
    'settings.notifications.note.title': 'Remarque:',
    'settings.notifications.note.description': 'Vous pouvez activer ou désactiver ces notifications à tout moment.',
    'settings.account.title': 'Gestion du compte',
    'settings.account.subtitle': 'Gérez votre compte ou supprimez-le',
    'settings.password.current.placeholder': 'Entrez le mot de passe actuel',
    'settings.password.new.placeholder': 'Entrez le nouveau mot de passe',
    'settings.password.confirm.placeholder': 'Entrez à nouveau le mot de passe',
    'settings.theme.light.description': 'Design clair avec des couleurs traditionnelles',
    'settings.theme.dark.description': 'Design sombre pour un travail confortable en faible luminosité',
    'settings.privacy.subtitle': 'Contrôlez quelles informations sont publiquement visibles',
    'settings.email.show.description': 'Rendre votre adresse email visible aux autres',
    'settings.phone.show.description': 'Rendre votre numéro de téléphone visible aux autres',
    'settings.saved': 'Paramètres Enregistrés',
  },
  it: {
    // Gender
    'gender.male': 'Maschile',
    'gender.female': 'Femminile',
    // Login
    'login.title': 'Accedi',
    'login.button': 'Accedi',
    'login.loading': 'Accesso in corso...',
    'login.register': 'crea un nuovo account',
    'login.or': 'Oppure',
    'login.email': 'Indirizzo email',
    'login.password': 'Password',
    'login.rememberMe': 'Resta connesso',
    'login.forgotPassword': 'Password dimenticata?',
    // Chat
    'chat.writeMessage': 'Scrivi un messaggio...',
    'chat.addEmoji': 'Aggiungi emoji',
    // Common
    'common.save': 'Salva',
    'common.cancel': 'Annulla',
    'common.delete': 'Elimina',
    'common.edit': 'Modifica',
    'common.search': 'Cerca',
    'common.filter': 'Filtra',
    'common.loading': 'Caricamento...',
    'common.error': 'Errore',
    'common.success': 'Successo',
    'common.back': 'Indietro',
    'common.next': 'Avanti',
    'common.submit': 'Invia',
    // Navigation
    'nav.home': 'Home',
    'nav.players': 'Giocatori',
    'nav.recruiters': 'Reclutatori',
    'nav.clubs': 'Club',
    'nav.about': 'Chi siamo',
    'nav.settings': 'Impostazioni',
    'nav.logout': 'Disconnetti',
    'nav.login': 'Accedi',
    'nav.register': 'Registrati',
    // Settings
    'settings.title': 'Impostazioni',
    'settings.subtitle': 'Gestisci le tue preferenze e impostazioni account',
    'settings.appearance': 'Aspetto',
    'settings.security': 'Login & Sicurezza',
    'settings.language': 'Lingua',
    'settings.notifications': 'Notifiche',
    'settings.account': 'Gestione account',
    'settings.appearance.title': 'Aspetto',
    'settings.appearance.subtitle': 'Personalizza l\'aspetto di Habicht',
    'settings.theme': 'Modalità tema',
    'settings.theme.light': 'Chiaro',
    'settings.theme.dark': 'Scuro',
    'settings.theme.light.desc': 'Design chiaro con colori tradizionali',
    'settings.theme.dark.desc': 'Design scuro per un lavoro confortevole con poca luce',
    'settings.security.title': 'Login & Sicurezza',
    'settings.security.subtitle': 'Gestisci la tua password e impostazioni di sicurezza',
    'settings.privacy': 'Privacy',
    'settings.privacy.desc': 'Controlla quali informazioni sono pubblicamente visibili',
    'settings.email.show': 'Visualizzazione indirizzo email',
    'settings.email.show.desc': 'Rendi il tuo indirizzo email visibile agli altri',
    'settings.phone.show': 'Visualizzazione numero di telefono',
    'settings.phone.show.desc': 'Rendi il tuo numero di telefono visibile agli altri',
    'settings.email': 'Indirizzo email',
    'settings.password.change': 'Cambia password',
    'settings.password.current': 'Password attuale',
    'settings.password.new': 'Nuova password',
    'settings.password.confirm': 'Conferma password',
    'settings.password.button': 'Cambia password',
    'settings.language.title': 'Lingua',
    'settings.language.subtitle': 'Scegli la tua lingua preferita',
    'settings.notifications.title': 'Notifiche',
    'settings.notifications.subtitle': 'Definisci quali notifiche email desideri ricevere',
    'settings.notifications.chat': '💬 Messaggi Chat',
    'settings.notifications.chat.description': 'Ricevi notifiche email per nuovi messaggi chat',
    'settings.notifications.playerLooking': '🏐 Giocatore Cerca un Club',
    'settings.notifications.playerLooking.description': 'Notifiche quando un giocatore sta cercando attivamente un club',
    'settings.notifications.recruiterSearching': '🔍 Reclutatore Cerca un Giocatore',
    'settings.notifications.recruiterSearching.description': 'Notifiche quando i reclutatori cercano attivamente giocatori',
    'settings.notifications.note.title': 'Nota:',
    'settings.notifications.note.description': 'Puoi attivare o disattivare queste notifiche in qualsiasi momento.',
    'settings.account.title': 'Gestione account',
    'settings.account.subtitle': 'Gestisci il tuo account o eliminalo',
    'settings.password.current.placeholder': 'Inserisci la password attuale',
    'settings.password.new.placeholder': 'Inserisci la nuova password',
    'settings.password.confirm.placeholder': 'Inserisci nuovamente la password',
    'settings.theme.light.description': 'Design chiaro con colori tradizionali',
    'settings.theme.dark.description': 'Design scuro per un lavoro confortevole con poca luce',
    'settings.privacy.subtitle': 'Controlla quali informazioni sono pubblicamente visibili',
    'settings.email.show.description': 'Rendi il tuo indirizzo email visibile agli altri',
    'settings.phone.show.description': 'Rendi il tuo numero di telefono visibile agli altri',
    'settings.saved': 'Impostazioni Salvate',
  },
  rm: {
    // Gender
    'gender.male': 'Masculin',
    'gender.female': 'Feminin',
    // Login
    'login.title': 'S\'annunziar',
    'login.button': 'S\'annunziar',
    'login.loading': 'Annunzia en cours...',
    'login.register': 'crear in nov conto',
    'login.or': 'U',
    'login.email': 'Adressa d\'email',
    'login.password': 'Pled-clav',
    'login.rememberMe': 'Restar annunzià',
    'login.forgotPassword': 'Emblidà il pled-clav?',
    // Chat
    'chat.writeMessage': 'Scriver in messadi...',
    'chat.addEmoji': 'Agiuntar emoji',
    // Common
    'common.save': 'Memorisar',
    'common.cancel': 'Interrumper',
    'common.delete': 'Stizzar',
    'common.edit': 'Modifitgar',
    'common.search': 'Tschertgar',
    'common.filter': 'Filtrar',
    'common.loading': 'Chargiar...',
    'common.error': 'Errur',
    'common.success': 'Success',
    'common.back': 'Enavos',
    'common.next': 'Vinavant',
    'common.submit': 'Trametter',
    // Navigation
    'nav.home': 'Pagina principala',
    'nav.players': 'Giugaders',
    'nav.recruiters': 'Recrutaders',
    'nav.clubs': 'Clubs',
    'nav.about': 'Davart nus',
    'nav.settings': 'Parameters',
    'nav.logout': 'S\'annunziar ora',
    'nav.login': 'S\'annunziar',
    'nav.register': 'S\'annunziar',
    // Settings
    'settings.title': 'Parameters',
    'settings.subtitle': 'Administrar tias preferenzas e parameters dal conto',
    'settings.appearance': 'Aspiet',
    'settings.security': 'Login & Segirezza',
    'settings.language': 'Linguatg',
    'settings.notifications': 'Communicaziuns',
    'settings.account': 'Administraziun dal conto',
    'settings.appearance.title': 'Aspiet',
    'settings.appearance.subtitle': 'Persunalisar l\'aspiet da Habicht',
    'settings.theme': 'Modus tema',
    'settings.theme.light': 'Cler',
    'settings.theme.dark': 'Stgir',
    'settings.theme.light.desc': 'Design cler cun colurs tradiziunalas',
    'settings.theme.dark.desc': 'Design stgir per lavurar confortabel cun pauc glisch',
    'settings.security.title': 'Login & Segirezza',
    'settings.security.subtitle': 'Administrar tia plauncha ed parameters da segirezza',
    'settings.privacy': 'Protecziun da datas',
    'settings.privacy.desc': 'Controllar tgeninas infurmaziuns èn publicas',
    'settings.email.show': 'Mussar adressa dad email',
    'settings.email.show.desc': 'Render tia adressa dad email visibla per auters',
    'settings.phone.show': 'Mussar numer da telefon',
    'settings.phone.show.desc': 'Render tes numer da telefon visibel per auters',
    'settings.email': 'Adressa dad email',
    'settings.password.change': 'Midar pled-clav',
    'settings.password.current': 'Pled-clav actual',
    'settings.password.new': 'Nov pled-clav',
    'settings.password.confirm': 'Confermar pled-clav',
    'settings.password.button': 'Midar pled-clav',
    'settings.language.title': 'Linguatg',
    'settings.language.subtitle': 'Tscherner tes linguatg preferì',
    'settings.notifications.title': 'Communicaziuns',
    'settings.notifications.subtitle': 'Definir tge communicaziuns dad email che ti vuls retschever',
    'settings.notifications.chat': '💬 Messadis da chat',
    'settings.notifications.chat.description': 'Retschever communicaziuns dad email per novs messadis da chat',
    'settings.notifications.playerLooking': '🏐 Giugader tschertga in club',
    'settings.notifications.playerLooking.description': 'Communicaziuns sch\'in giugader tschertga activamain in club',
    'settings.notifications.recruiterSearching': '🔍 Recrutader tschertga giugaders',
    'settings.notifications.recruiterSearching.description': 'Communicaziuns sch\'ils recrutaders tschertgan activamain giugaders',
    'settings.notifications.note.title': 'Remartga:',
    'settings.notifications.note.description': 'Ti pos activar u deactivar questas communicaziuns da tut temp.',
    'settings.account.title': 'Administraziun dal conto',
    'settings.account.subtitle': 'Administrar tes conto u stizzal',
    'settings.password.current.placeholder': 'Endatar il pled-clav actual',
    'settings.password.new.placeholder': 'Endatar il nov pled-clav',
    'settings.password.confirm.placeholder': 'Endatar danovamain il pled-clav',
    'settings.theme.light.description': 'Design cler cun colurs tradiziunalas',
    'settings.theme.dark.description': 'Design stgir per lavurar confortabel cun pauc glisch',
    'settings.privacy.subtitle': 'Controllar tgeninas infurmaziuns èn publicas',
    'settings.email.show.description': 'Render tia adressa dad email visibla per auters',
    'settings.phone.show.description': 'Render tes numer da telefon visibel per auters',
    'settings.saved': 'Parameters Memorisads',
  },
  en: {
    // Gender
    'gender.male': 'Male',
    'gender.female': 'Female',
    // Login
    'login.title': 'Login',
    'login.button': 'Login',
    'login.loading': 'Logging in...',
    'login.register': 'create a new account',
    'login.or': 'Or',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot password?',
    // Chat
    'chat.writeMessage': 'Write a message...',
    'chat.addEmoji': 'Add emoji',
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.submit': 'Submit',
    // Navigation
    'nav.home': 'Home',
    'nav.players': 'Players',
    'nav.recruiters': 'Recruiters',
    'nav.clubs': 'Clubs',
    'nav.about': 'About',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'nav.login': 'Login',
    'nav.register': 'Register',
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your preferences and account settings',
    'settings.appearance': 'Appearance',
    'settings.security': 'Login & Security',
    'settings.language': 'Language',
    'settings.notifications': 'Notifications',
    'settings.account': 'Account Management',
    'settings.appearance.title': 'Appearance',
    'settings.appearance.subtitle': 'Customize how Habicht looks for you',
    'settings.theme': 'Theme Mode',
    'settings.theme.light': 'Light',
    'settings.theme.dark': 'Dark',
    'settings.theme.light.desc': 'Light design with traditional colors',
    'settings.theme.dark.desc': 'Dark design for comfortable work in low light',
    'settings.security.title': 'Login & Security',
    'settings.security.subtitle': 'Manage your password and security settings',
    'settings.privacy': 'Privacy',
    'settings.privacy.desc': 'Control which information is publicly visible',
    'settings.email.show': 'Email Address Display',
    'settings.email.show.desc': 'Make your email address visible to others',
    'settings.phone.show': 'Phone Number Display',
    'settings.phone.show.desc': 'Make your phone number visible to others',
    'settings.email': 'Email Address',
    'settings.password.change': 'Change Password',
    'settings.password.current': 'Current Password',
    'settings.password.new': 'New Password',
    'settings.password.confirm': 'Confirm Password',
    'settings.password.button': 'Change password',
    'settings.language.title': 'Language',
    'settings.language.subtitle': 'Choose your preferred language',
    'settings.notifications.title': 'Notifications',
    'settings.notifications.subtitle': 'Set which email notifications you want to receive',
    'settings.notifications.chat': '💬 Chat Messages',
    'settings.notifications.chat.description': 'Receive email notifications for new chat messages',
    'settings.notifications.playerLooking': '🏐 Player Looking for Club',
    'settings.notifications.playerLooking.description': 'Notifications when a player is actively looking for a club',
    'settings.notifications.recruiterSearching': '🔍 Recruiter Searching for Players',
    'settings.notifications.recruiterSearching.description': 'Notifications when recruiters are actively searching for players',
    'settings.notifications.note.title': 'Note:',
    'settings.notifications.note.description': 'You can enable or disable these notifications at any time.',
    'settings.account.title': 'Account Management',
    'settings.account.subtitle': 'Manage your account or delete it',
    'settings.password.current.placeholder': 'Enter current password',
    'settings.password.new.placeholder': 'Enter new password',
    'settings.password.confirm.placeholder': 'Enter password again',
    'settings.theme.light.description': 'Light design with traditional colors',
    'settings.theme.dark.description': 'Dark design for comfortable work in low light',
    'settings.privacy.subtitle': 'Control which information is publicly visible',
    'settings.email.show.description': 'Make your email address visible to others',
    'settings.phone.show.description': 'Make your phone number visible to others',
    'settings.saved': 'Settings Saved',
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('gsw')

  useEffect(() => {
    // Load language from localStorage on mount
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && ['gsw', 'de', 'fr', 'it', 'rm', 'en'].includes(savedLanguage)) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    // Swiss German (gsw) is the default language - no translation needed
    // For other languages, translation happens automatically via <Translate> component
    if (lang !== 'gsw') {
      console.log(`Language changed to ${lang} - content will be translated automatically`)
    }
    setLanguageState(lang)
    localStorage.setItem('language', lang)
    // Language changes dynamically without reload, similar to browser translate extension
  }

  const t = (key: string): string => {
    const keys = key.split('.')
    let value: any = translations[language]
    
    for (const k of keys) {
      if (value && typeof value === 'object') {
        value = value[k]
      } else {
        return key // Return key if translation not found
      }
    }
    
    return typeof value === 'string' ? value : key
  }

  // Dynamic translation using Google Translate API
  const translate = async (text: string, sourceLanguage: string = 'gsw'): Promise<string> => {
    const targetLanguageCode = getGoogleLanguageCode(language)
    return await translateText(text, targetLanguageCode, sourceLanguage)
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translate }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
